name: Node.JS test CI CD

#events
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        #scelta del tipo di runner (VM)
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Usa Node.JS ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run build --if-present
            - run: npm test

    docker-build-and-push:
      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'

      steps:
        - uses: actions/checkout@v2

        - name: LogIn su Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USER }}
            password: ${{ secrets.DOCKER_HUB_PASS }}

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile
            push: true
            tags: braintechinno/cicd-node-rest-test
